#region

using UnityEngine;

#endregion

namespace Appalachia.Utility.Colors
{
    public static partial class Colors
    {
        
        public static ColorRef ToRef(this Color c)
        {
            return c;
        }

        public static Color ToColor(this Enum c)
        {
            return FromEnum(c);
        }

        public static Color FromEnum(Enum c)
        {
            switch (c)
            {
                case Enum.Black:
                    return Black;
                case Enum.Gray01:
                    return Gray01;
                case Enum.Gray02:
                    return Gray02;
                case Enum.Gray03:
                    return Gray03;
                case Enum.Gray04:
                    return Gray04;
                case Enum.Gray05:
                    return Gray05;
                case Enum.Gray06:
                    return Gray06;
                case Enum.Gray07:
                    return Gray07;
                case Enum.Gray08:
                    return Gray08;
                case Enum.Gray09:
                    return Gray09;
                case Enum.Gray10:
                    return Gray10;
                case Enum.Gray11:
                    return Gray11;
                case Enum.SgiGray12:
                    return SgiGray12;
                case Enum.Gray12:
                    return Gray12;
                case Enum.Gray13:
                    return Gray13;
                case Enum.Gray14:
                    return Gray14;
                case Enum.Gray15:
                    return Gray15;
                case Enum.SgiGray16:
                    return SgiGray16;
                case Enum.Gray16:
                    return Gray16;
                case Enum.Gray17:
                    return Gray17;
                case Enum.Gray18:
                    return Gray18;
                case Enum.Gray19:
                    return Gray19;
                case Enum.Gray20:
                    return Gray20;
                case Enum.Gray21:
                    return Gray21;
                case Enum.Gray22:
                    return Gray22;
                case Enum.Gray23:
                    return Gray23;
                case Enum.Gray24:
                    return Gray24;
                case Enum.Gray25:
                    return Gray25;
                case Enum.Gray26:
                    return Gray26;
                case Enum.Gray27:
                    return Gray27;
                case Enum.Gray28:
                    return Gray28;
                case Enum.Gray29:
                    return Gray29;
                case Enum.Gray30:
                    return Gray30;
                case Enum.Gray31:
                    return Gray31;
                case Enum.SgiGray32:
                    return SgiGray32;
                case Enum.Gray32:
                    return Gray32;
                case Enum.Gray33:
                    return Gray33;
                case Enum.SgiDarkGray:
                    return SgiDarkGray;
                case Enum.Gray34:
                    return Gray34;
                case Enum.Gray35:
                    return Gray35;
                case Enum.SgiGray36:
                    return SgiGray36;
                case Enum.Gray36:
                    return Gray36;
                case Enum.Gray37:
                    return Gray37;
                case Enum.Gray38:
                    return Gray38;
                case Enum.Gray39:
                    return Gray39;
                case Enum.Gray40:
                    return Gray40;
                case Enum.DimGrayGray42:
                    return DimGrayGray42;
                case Enum.Gray42:
                    return Gray42;
                case Enum.Gray43:
                    return Gray43;
                case Enum.Gray44:
                    return Gray44;
                case Enum.Gray45:
                    return Gray45;
                case Enum.Gray46:
                    return Gray46;
                case Enum.Gray47:
                    return Gray47;
                case Enum.Gray48:
                    return Gray48;
                case Enum.Gray49:
                    return Gray49;
                case Enum.Gray50:
                    return Gray50;
                case Enum.Gray:
                    return Gray;
                case Enum.Gray51:
                    return Gray51;
                case Enum.SgiGray52:
                    return SgiGray52;
                case Enum.Gray52:
                    return Gray52;
                case Enum.Gray53:
                    return Gray53;
                case Enum.Gray54:
                    return Gray54;
                case Enum.Gray55:
                    return Gray55;
                case Enum.SgiGray56:
                    return SgiGray56;
                case Enum.Gray56:
                    return Gray56;
                case Enum.Gray57:
                    return Gray57;
                case Enum.Gray58:
                    return Gray58;
                case Enum.Gray59:
                    return Gray59;
                case Enum.Gray60:
                    return Gray60;
                case Enum.Gray61:
                    return Gray61;
                case Enum.Gray62:
                    return Gray62;
                case Enum.Gray63:
                    return Gray63;
                case Enum.Gray64:
                    return Gray64;
                case Enum.Gray65:
                    return Gray65;
                case Enum.Gray66:
                    return Gray66;
                case Enum.DarkGray:
                    return DarkGray;
                case Enum.SgiLightGray:
                    return SgiLightGray;
                case Enum.Gray67:
                    return Gray67;
                case Enum.Gray68:
                    return Gray68;
                case Enum.Gray69:
                    return Gray69;
                case Enum.Gray70:
                    return Gray70;
                case Enum.Gray71:
                    return Gray71;
                case Enum.SgiGray72:
                    return SgiGray72;
                case Enum.Gray72:
                    return Gray72;
                case Enum.Gray73:
                    return Gray73;
                case Enum.Gray74:
                    return Gray74;
                case Enum.Gray75:
                    return Gray75;
                case Enum.SgiGray76:
                    return SgiGray76;
                case Enum.Silver:
                    return Silver;
                case Enum.Gray76:
                    return Gray76;
                case Enum.Gray77:
                    return Gray77;
                case Enum.Gray78:
                    return Gray78;
                case Enum.Gray79:
                    return Gray79;
                case Enum.Gray80:
                    return Gray80;
                case Enum.Gray81:
                    return Gray81;
                case Enum.Gray82:
                    return Gray82;
                case Enum.LightGray:
                    return LightGray;
                case Enum.Gray83:
                    return Gray83;
                case Enum.Gray84:
                    return Gray84;
                case Enum.Gray85:
                    return Gray85;
                case Enum.Gray86:
                    return Gray86;
                case Enum.Gainsboro:
                    return Gainsboro;
                case Enum.Gray87:
                    return Gray87;
                case Enum.Gray88:
                    return Gray88;
                case Enum.Gray89:
                    return Gray89;
                case Enum.Gray90:
                    return Gray90;
                case Enum.Gray91:
                    return Gray91;
                case Enum.SgiGray92:
                    return SgiGray92;
                case Enum.Gray92:
                    return Gray92;
                case Enum.Gray93:
                    return Gray93;
                case Enum.Gray94:
                    return Gray94;
                case Enum.Gray95:
                    return Gray95;
                case Enum.SgiGray96:
                    return SgiGray96;
                case Enum.Gray97:
                    return Gray97;
                case Enum.WhiteSmokeGray96:
                    return WhiteSmokeGray96;
                case Enum.Gray98:
                    return Gray98;
                case Enum.Gray99:
                    return Gray99;
                case Enum.White:
                    return White;
                case Enum.Snow4:
                    return Snow4;
                case Enum.Snow3:
                    return Snow3;
                case Enum.Snow1:
                    return Snow1;
                case Enum.Snow2:
                    return Snow2;
                case Enum.RosyBrown:
                    return RosyBrown;
                case Enum.RosyBrown4:
                    return RosyBrown4;
                case Enum.RosyBrown3:
                    return RosyBrown3;
                case Enum.RosyBrown2:
                    return RosyBrown2;
                case Enum.RosyBrown1:
                    return RosyBrown1;
                case Enum.SgiSalmon:
                    return SgiSalmon;
                case Enum.LightCoral:
                    return LightCoral;
                case Enum.IndianRed:
                    return IndianRed;
                case Enum.IndianRed4:
                    return IndianRed4;
                case Enum.IndianRed3:
                    return IndianRed3;
                case Enum.IndianRed2:
                    return IndianRed2;
                case Enum.IndianRed1:
                    return IndianRed1;
                case Enum.Brown4:
                    return Brown4;
                case Enum.Brown:
                    return Brown;
                case Enum.Brown1:
                    return Brown1;
                case Enum.Brown3:
                    return Brown3;
                case Enum.Brown2:
                    return Brown2;
                case Enum.FireBrick:
                    return FireBrick;
                case Enum.FireBrick4:
                    return FireBrick4;
                case Enum.FireBrick3:
                    return FireBrick3;
                case Enum.FireBrick2:
                    return FireBrick2;
                case Enum.FireBrick1:
                    return FireBrick1;
                case Enum.Maroon:
                    return Maroon;
                case Enum.Red4DarkRed:
                    return Red4DarkRed;
                case Enum.Red3:
                    return Red3;
                case Enum.Red2:
                    return Red2;
                case Enum.Red1:
                    return Red1;
                case Enum.MistyRose3:
                    return MistyRose3;
                case Enum.MistyRose2:
                    return MistyRose2;
                case Enum.MistyRose1:
                    return MistyRose1;
                case Enum.Salmon:
                    return Salmon;
                case Enum.MistyRose4:
                    return MistyRose4;
                case Enum.Tomato3:
                    return Tomato3;
                case Enum.BurntUmber:
                    return BurntUmber;
                case Enum.Coral4:
                    return Coral4;
                case Enum.Coral3:
                    return Coral3;
                case Enum.Coral2:
                    return Coral2;
                case Enum.Coral1:
                    return Coral1;
                case Enum.Tomato4:
                    return Tomato4;
                case Enum.Tomato2:
                    return Tomato2;
                case Enum.Tomato1:
                    return Tomato1;
                case Enum.Salmon4:
                    return Salmon4;
                case Enum.Salmon2:
                    return Salmon2;
                case Enum.Salmon3:
                    return Salmon3;
                case Enum.Salmon1:
                    return Salmon1;
                case Enum.DarkSalmon:
                    return DarkSalmon;
                case Enum.Sepia:
                    return Sepia;
                case Enum.OrangeRed4:
                    return OrangeRed4;
                case Enum.LightSalmon2:
                    return LightSalmon2;
                case Enum.Coral:
                    return Coral;
                case Enum.OrangeRed3:
                    return OrangeRed3;
                case Enum.OrangeRed2:
                    return OrangeRed2;
                case Enum.OrangeRed1:
                    return OrangeRed1;
                case Enum.LightSalmon4:
                    return LightSalmon4;
                case Enum.LightSalmon3:
                    return LightSalmon3;
                case Enum.LightSalmon1:
                    return LightSalmon1;
                case Enum.Sienna:
                    return Sienna;
                case Enum.Sienna4:
                    return Sienna4;
                case Enum.Sienna3:
                    return Sienna3;
                case Enum.Sienna2:
                    return Sienna2;
                case Enum.Sienna1:
                    return Sienna1;
                case Enum.Flesh:
                    return Flesh;
                case Enum.BurntSienna:
                    return BurntSienna;
                case Enum.IvoryBlack:
                    return IvoryBlack;
                case Enum.CadmiumOrange:
                    return CadmiumOrange;
                case Enum.Seashell1:
                    return Seashell1;
                case Enum.Chocolate3:
                    return Chocolate3;
                case Enum.Chocolate1:
                    return Chocolate1;
                case Enum.Chocolate2:
                    return Chocolate2;
                case Enum.Seashell3:
                    return Seashell3;
                case Enum.Chocolate:
                    return Chocolate;
                case Enum.Chocolate4:
                    return Chocolate4;
                case Enum.RawSienna:
                    return RawSienna;
                case Enum.Seashell4:
                    return Seashell4;
                case Enum.Seashell2:
                    return Seashell2;
                case Enum.Peachpuff3:
                    return Peachpuff3;
                case Enum.Peachpuff2:
                    return Peachpuff2;
                case Enum.SandyBrown:
                    return SandyBrown;
                case Enum.Peachpuff4:
                    return Peachpuff4;
                case Enum.Peachpuff1:
                    return Peachpuff1;
                case Enum.Tan4:
                    return Tan4;
                case Enum.Tan3:
                    return Tan3;
                case Enum.Tan2:
                    return Tan2;
                case Enum.Tan1:
                    return Tan1;
                case Enum.DarkOrange4:
                    return DarkOrange4;
                case Enum.DarkOrange3:
                    return DarkOrange3;
                case Enum.DarkOrange2:
                    return DarkOrange2;
                case Enum.DarkOrange1:
                    return DarkOrange1;
                case Enum.Linen:
                    return Linen;
                case Enum.Melon:
                    return Melon;
                case Enum.Orange:
                    return Orange;
                case Enum.Bisque3:
                    return Bisque3;
                case Enum.Bisque2:
                    return Bisque2;
                case Enum.Bisque1:
                    return Bisque1;
                case Enum.Carrot:
                    return Carrot;
                case Enum.DarkOrange:
                    return DarkOrange;
                case Enum.AntiqueWhite3:
                    return AntiqueWhite3;
                case Enum.AntiqueWhite2:
                    return AntiqueWhite2;
                case Enum.AntiqueWhite1:
                    return AntiqueWhite1;
                case Enum.Bisque4:
                    return Bisque4;
                case Enum.Burlywood4:
                    return Burlywood4;
                case Enum.Burlywood3:
                    return Burlywood3;
                case Enum.Burlywood:
                    return Burlywood;
                case Enum.Burlywood2:
                    return Burlywood2;
                case Enum.Burlywood1:
                    return Burlywood1;
                case Enum.AntiqueWhite4:
                    return AntiqueWhite4;
                case Enum.AntiqueWhite:
                    return AntiqueWhite;
                case Enum.Eggshell:
                    return Eggshell;
                case Enum.Tan:
                    return Tan;
                case Enum.Brick:
                    return Brick;
                case Enum.CadmiumYellow:
                    return CadmiumYellow;
                case Enum.NavajoWhite2:
                    return NavajoWhite2;
                case Enum.NavajoWhite1:
                    return NavajoWhite1;
                case Enum.BlanchedAlmond:
                    return BlanchedAlmond;
                case Enum.NavajoWhite4:
                    return NavajoWhite4;
                case Enum.NavajoWhite3:
                    return NavajoWhite3;
                case Enum.PapayaWhip:
                    return PapayaWhip;
                case Enum.Wheat4:
                    return Wheat4;
                case Enum.Moccasin:
                    return Moccasin;
                case Enum.Orange4:
                    return Orange4;
                case Enum.Orange3:
                    return Orange3;
                case Enum.Orange2:
                    return Orange2;
                case Enum.Orange1:
                    return Orange1;
                case Enum.FloralWhite:
                    return FloralWhite;
                case Enum.OldLace:
                    return OldLace;
                case Enum.Wheat3:
                    return Wheat3;
                case Enum.Wheat2:
                    return Wheat2;
                case Enum.Wheat:
                    return Wheat;
                case Enum.Wheat1:
                    return Wheat1;
                case Enum.Goldenrod4:
                    return Goldenrod4;
                case Enum.Goldenrod3:
                    return Goldenrod3;
                case Enum.Goldenrod:
                    return Goldenrod;
                case Enum.Goldenrod2:
                    return Goldenrod2;
                case Enum.Goldenrod1:
                    return Goldenrod1;
                case Enum.DarkGoldenrod4:
                    return DarkGoldenrod4;
                case Enum.DarkGoldenrod:
                    return DarkGoldenrod;
                case Enum.DarkGoldenrod3:
                    return DarkGoldenrod3;
                case Enum.DarkGoldenrod2:
                    return DarkGoldenrod2;
                case Enum.DarkGoldenrod1:
                    return DarkGoldenrod1;
                case Enum.Cornsilk1:
                    return Cornsilk1;
                case Enum.Cornsilk3:
                    return Cornsilk3;
                case Enum.Cornsilk2:
                    return Cornsilk2;
                case Enum.Cornsilk4:
                    return Cornsilk4;
                case Enum.LightGoldenrod4:
                    return LightGoldenrod4;
                case Enum.LightGoldenrod3:
                    return LightGoldenrod3;
                case Enum.LightGoldenrod2:
                    return LightGoldenrod2;
                case Enum.LightGoldenrod1:
                    return LightGoldenrod1;
                case Enum.Gold4:
                    return Gold4;
                case Enum.Gold3:
                    return Gold3;
                case Enum.Gold2:
                    return Gold2;
                case Enum.Gold1:
                    return Gold1;
                case Enum.SgiBrightGray:
                    return SgiBrightGray;
                case Enum.Banana:
                    return Banana;
                case Enum.LemonChiffon2:
                    return LemonChiffon2;
                case Enum.LemonChiffon3:
                    return LemonChiffon3;
                case Enum.LemonChiffon1:
                    return LemonChiffon1;
                case Enum.PaleGoldenrod:
                    return PaleGoldenrod;
                case Enum.Khaki:
                    return Khaki;
                case Enum.LemonChiffon4:
                    return LemonChiffon4;
                case Enum.Khaki4:
                    return Khaki4;
                case Enum.DarkKhaki:
                    return DarkKhaki;
                case Enum.Khaki3:
                    return Khaki3;
                case Enum.Khaki1:
                    return Khaki1;
                case Enum.Khaki2:
                    return Khaki2;
                case Enum.Ivory4:
                    return Ivory4;
                case Enum.Ivory3:
                    return Ivory3;
                case Enum.Ivory2:
                    return Ivory2;
                case Enum.Ivory1:
                    return Ivory1;
                case Enum.Beige:
                    return Beige;
                case Enum.LightYellow4:
                    return LightYellow4;
                case Enum.LightYellow3:
                    return LightYellow3;
                case Enum.LightYellow2:
                    return LightYellow2;
                case Enum.LightYellow1:
                    return LightYellow1;
                case Enum.LightGoldenrodYellow:
                    return LightGoldenrodYellow;
                case Enum.WarmGray:
                    return WarmGray;
                case Enum.SgiOliveDrab:
                    return SgiOliveDrab;
                case Enum.Olive:
                    return Olive;
                case Enum.Yellow4:
                    return Yellow4;
                case Enum.Yellow3:
                    return Yellow3;
                case Enum.Yellow2:
                    return Yellow2;
                case Enum.Yellow1:
                    return Yellow1;
                case Enum.OliveDrab4:
                    return OliveDrab4;
                case Enum.OliveDrab:
                    return OliveDrab;
                case Enum.OliveDrab3:
                    return OliveDrab3;
                case Enum.OliveDrab2:
                    return OliveDrab2;
                case Enum.OliveDrab1:
                    return OliveDrab1;
                case Enum.DarkOliveGreen:
                    return DarkOliveGreen;
                case Enum.DarkOliveGreen4:
                    return DarkOliveGreen4;
                case Enum.DarkOliveGreen3:
                    return DarkOliveGreen3;
                case Enum.DarkOliveGreen2:
                    return DarkOliveGreen2;
                case Enum.DarkOliveGreen1:
                    return DarkOliveGreen1;
                case Enum.GreenYellow:
                    return GreenYellow;
                case Enum.Chartreuse4:
                    return Chartreuse4;
                case Enum.Chartreuse3:
                    return Chartreuse3;
                case Enum.Chartreuse2:
                    return Chartreuse2;
                case Enum.LawnGreen:
                    return LawnGreen;
                case Enum.Chartreuse1:
                    return Chartreuse1;
                case Enum.SapGreen:
                    return SapGreen;
                case Enum.Honeydew4:
                    return Honeydew4;
                case Enum.Honeydew3:
                    return Honeydew3;
                case Enum.Honeydew2:
                    return Honeydew2;
                case Enum.Honeydew1:
                    return Honeydew1;
                case Enum.DarkSeaGreen:
                    return DarkSeaGreen;
                case Enum.DarkSeaGreen4:
                    return DarkSeaGreen4;
                case Enum.DarkSeaGreen3:
                    return DarkSeaGreen3;
                case Enum.DarkSeaGreen2:
                    return DarkSeaGreen2;
                case Enum.DarkSeaGreen1:
                    return DarkSeaGreen1;
                case Enum.PaleGreen4:
                    return PaleGreen4;
                case Enum.PaleGreen3:
                    return PaleGreen3;
                case Enum.PaleGreen2:
                    return PaleGreen2;
                case Enum.PaleGreen:
                    return PaleGreen;
                case Enum.PaleGreen1:
                    return PaleGreen1;
                case Enum.SgiChartreuse:
                    return SgiChartreuse;
                case Enum.ForestGreen:
                    return ForestGreen;
                case Enum.LimeGreen:
                    return LimeGreen;
                case Enum.DarkGreen:
                    return DarkGreen;
                case Enum.Green:
                    return Green;
                case Enum.Green4:
                    return Green4;
                case Enum.Green3:
                    return Green3;
                case Enum.Green2:
                    return Green2;
                case Enum.Green1:
                    return Green1;
                case Enum.CobaltGreen:
                    return CobaltGreen;
                case Enum.Mint:
                    return Mint;
                case Enum.EmeraldGreen:
                    return EmeraldGreen;
                case Enum.SeaGreen4:
                    return SeaGreen4;
                case Enum.MediumSeaGreen:
                    return MediumSeaGreen;
                case Enum.SeaGreen3:
                    return SeaGreen3;
                case Enum.SeaGreen2:
                    return SeaGreen2;
                case Enum.SeaGreen1:
                    return SeaGreen1;
                case Enum.MintCream:
                    return MintCream;
                case Enum.SpringGreen3:
                    return SpringGreen3;
                case Enum.SpringGreen2:
                    return SpringGreen2;
                case Enum.SpringGreen1:
                    return SpringGreen1;
                case Enum.SpringGreen:
                    return SpringGreen;
                case Enum.MediumSpringGreen:
                    return MediumSpringGreen;
                case Enum.Aquamarine3:
                    return Aquamarine3;
                case Enum.Aquamarine1:
                    return Aquamarine1;
                case Enum.Aquamarine4:
                    return Aquamarine4;
                case Enum.Aquamarine2:
                    return Aquamarine2;
                case Enum.ColdGray:
                    return ColdGray;
                case Enum.TurquoiseBlue:
                    return TurquoiseBlue;
                case Enum.Turquoise:
                    return Turquoise;
                case Enum.LightSeaGreen:
                    return LightSeaGreen;
                case Enum.ManganeseBlue:
                    return ManganeseBlue;
                case Enum.MediumTurquoise:
                    return MediumTurquoise;
                case Enum.Azure4:
                    return Azure4;
                case Enum.Azure3:
                    return Azure3;
                case Enum.Azure2:
                    return Azure2;
                case Enum.Azure1:
                    return Azure1;
                case Enum.LightCyan4:
                    return LightCyan4;
                case Enum.LightCyan3:
                    return LightCyan3;
                case Enum.LightCyan2:
                    return LightCyan2;
                case Enum.LightCyan1:
                    return LightCyan1;
                case Enum.PaleTurquoise4:
                    return PaleTurquoise4;
                case Enum.PaleTurquoise3:
                    return PaleTurquoise3;
                case Enum.PaleTurquoise2:
                    return PaleTurquoise2;
                case Enum.PaleTurquoise1:
                    return PaleTurquoise1;
                case Enum.DarkSlateGray:
                    return DarkSlateGray;
                case Enum.DarkSlateGray3:
                    return DarkSlateGray3;
                case Enum.DarkSlateGray2:
                    return DarkSlateGray2;
                case Enum.DarkSlateGray1:
                    return DarkSlateGray1;
                case Enum.DarkSlateGray4:
                    return DarkSlateGray4;
                case Enum.SgiTeal:
                    return SgiTeal;
                case Enum.Teal:
                    return Teal;
                case Enum.Cyan4:
                    return Cyan4;
                case Enum.Cyan3:
                    return Cyan3;
                case Enum.DarkTurquoise:
                    return DarkTurquoise;
                case Enum.Cyan2:
                    return Cyan2;
                case Enum.Cyan:
                    return Cyan;
                case Enum.CadetBlue:
                    return CadetBlue;
                case Enum.Turquoise4:
                    return Turquoise4;
                case Enum.Turquoise3:
                    return Turquoise3;
                case Enum.Turquoise2:
                    return Turquoise2;
                case Enum.Turquoise1:
                    return Turquoise1;
                case Enum.CadetBlue4:
                    return CadetBlue4;
                case Enum.CadetBlue3:
                    return CadetBlue3;
                case Enum.CadetBlue2:
                    return CadetBlue2;
                case Enum.CadetBlue1:
                    return CadetBlue1;
                case Enum.PowderBlue:
                    return PowderBlue;
                case Enum.LightBlue4:
                    return LightBlue4;
                case Enum.LightBlue:
                    return LightBlue;
                case Enum.DeepSkyBlue3:
                    return DeepSkyBlue3;
                case Enum.LightBlue3:
                    return LightBlue3;
                case Enum.LightBlue2:
                    return LightBlue2;
                case Enum.LightBlue1:
                    return LightBlue1;
                case Enum.DeepSkyBlue4:
                    return DeepSkyBlue4;
                case Enum.DeepSkyBlue2:
                    return DeepSkyBlue2;
                case Enum.DeepSkyBlue1:
                    return DeepSkyBlue1;
                case Enum.Peacock:
                    return Peacock;
                case Enum.SkyBlue:
                    return SkyBlue;
                case Enum.LightSkyBlue3:
                    return LightSkyBlue3;
                case Enum.LightSkyBlue2:
                    return LightSkyBlue2;
                case Enum.LightSkyBlue4:
                    return LightSkyBlue4;
                case Enum.LightSkyBlue1:
                    return LightSkyBlue1;
                case Enum.LightSkyBlue:
                    return LightSkyBlue;
                case Enum.SkyBlue4:
                    return SkyBlue4;
                case Enum.SkyBlue3:
                    return SkyBlue3;
                case Enum.SkyBlue2:
                    return SkyBlue2;
                case Enum.SkyBlue1:
                    return SkyBlue1;
                case Enum.SteelBlue4:
                    return SteelBlue4;
                case Enum.SteelBlue:
                    return SteelBlue;
                case Enum.SteelBlue3:
                    return SteelBlue3;
                case Enum.SteelBlue2:
                    return SteelBlue2;
                case Enum.SteelBlue1:
                    return SteelBlue1;
                case Enum.AliceBlue:
                    return AliceBlue;
                case Enum.DodgerBlue4:
                    return DodgerBlue4;
                case Enum.DodgerBlue3:
                    return DodgerBlue3;
                case Enum.DodgerBlue2:
                    return DodgerBlue2;
                case Enum.DodgerBlue1:
                    return DodgerBlue1;
                case Enum.SlateGray4:
                    return SlateGray4;
                case Enum.SlateGray:
                    return SlateGray;
                case Enum.LightSlateGray:
                    return LightSlateGray;
                case Enum.SlateGray3:
                    return SlateGray3;
                case Enum.SlateGray2:
                    return SlateGray2;
                case Enum.SlateGray1:
                    return SlateGray1;
                case Enum.SgiLightBlue:
                    return SgiLightBlue;
                case Enum.LightSteelBlue4:
                    return LightSteelBlue4;
                case Enum.LightSteelBlue3:
                    return LightSteelBlue3;
                case Enum.LightSteelBlue:
                    return LightSteelBlue;
                case Enum.LightSteelBlue1:
                    return LightSteelBlue1;
                case Enum.LightSteelBlue2:
                    return LightSteelBlue2;
                case Enum.CornflowerBlue:
                    return CornflowerBlue;
                case Enum.Cobalt:
                    return Cobalt;
                case Enum.RoyalBlue3:
                    return RoyalBlue3;
                case Enum.RoyalBlue2:
                    return RoyalBlue2;
                case Enum.RoyalBlue1:
                    return RoyalBlue1;
                case Enum.RoyalBlue4:
                    return RoyalBlue4;
                case Enum.RoyalBlue:
                    return RoyalBlue;
                case Enum.GhostWhite:
                    return GhostWhite;
                case Enum.Lavender:
                    return Lavender;
                case Enum.SgiSlateBlue:
                    return SgiSlateBlue;
                case Enum.MidnightBlue:
                    return MidnightBlue;
                case Enum.Navy:
                    return Navy;
                case Enum.Blue4:
                    return Blue4;
                case Enum.Blue3:
                    return Blue3;
                case Enum.Blue2:
                    return Blue2;
                case Enum.Blue:
                    return Blue;
                case Enum.DarkSlateBlue:
                    return DarkSlateBlue;
                case Enum.SlateBlue4:
                    return SlateBlue4;
                case Enum.SlateBlue:
                    return SlateBlue;
                case Enum.SlateBlue3:
                    return SlateBlue3;
                case Enum.MediumSlateBlue:
                    return MediumSlateBlue;
                case Enum.SlateBlue2:
                    return SlateBlue2;
                case Enum.LightSlateBlue:
                    return LightSlateBlue;
                case Enum.SlateBlue1:
                    return SlateBlue1;
                case Enum.MediumPurple4:
                    return MediumPurple4;
                case Enum.MediumPurple:
                    return MediumPurple;
                case Enum.MediumPurple3:
                    return MediumPurple3;
                case Enum.MediumPurple2:
                    return MediumPurple2;
                case Enum.MediumPurple1:
                    return MediumPurple1;
                case Enum.BlueViolet:
                    return BlueViolet;
                case Enum.Purple4:
                    return Purple4;
                case Enum.Purple3:
                    return Purple3;
                case Enum.Purple2:
                    return Purple2;
                case Enum.Purple1:
                    return Purple1;
                case Enum.Indigo:
                    return Indigo;
                case Enum.DarkOrchid4:
                    return DarkOrchid4;
                case Enum.DarkOrchid:
                    return DarkOrchid;
                case Enum.DarkOrchid3:
                    return DarkOrchid3;
                case Enum.DarkOrchid2:
                    return DarkOrchid2;
                case Enum.DarkOrchid1:
                    return DarkOrchid1;
                case Enum.DarkViolet:
                    return DarkViolet;
                case Enum.MediumOrchid4:
                    return MediumOrchid4;
                case Enum.MediumOrchid3:
                    return MediumOrchid3;
                case Enum.MediumOrchid2:
                    return MediumOrchid2;
                case Enum.MediumOrchid1:
                    return MediumOrchid1;
                case Enum.MediumOrchid:
                    return MediumOrchid;
                case Enum.Thistle4:
                    return Thistle4;
                case Enum.Thistle3:
                    return Thistle3;
                case Enum.Thistle:
                    return Thistle;
                case Enum.Thistle2:
                    return Thistle2;
                case Enum.Thistle1:
                    return Thistle1;
                case Enum.Plum4:
                    return Plum4;
                case Enum.Plum3:
                    return Plum3;
                case Enum.Plum2:
                    return Plum2;
                case Enum.Plum1:
                    return Plum1;
                case Enum.Plum:
                    return Plum;
                case Enum.Violet:
                    return Violet;
                case Enum.SgiBeet:
                    return SgiBeet;
                case Enum.Purple:
                    return Purple;
                case Enum.Magenta4:
                    return Magenta4;
                case Enum.Magenta3:
                    return Magenta3;
                case Enum.Magenta2:
                    return Magenta2;
                case Enum.Magenta:
                    return Magenta;
                case Enum.Orchid4:
                    return Orchid4;
                case Enum.Orchid3:
                    return Orchid3;
                case Enum.Orchid:
                    return Orchid;
                case Enum.Orchid2:
                    return Orchid2;
                case Enum.Orchid1:
                    return Orchid1;
                case Enum.VioletRed:
                    return VioletRed;
                case Enum.Maroon4:
                    return Maroon4;
                case Enum.Maroon2:
                    return Maroon2;
                case Enum.Maroon1:
                    return Maroon1;
                case Enum.Maroon3:
                    return Maroon3;
                case Enum.MediumVioletRed:
                    return MediumVioletRed;
                case Enum.DeepPink4:
                    return DeepPink4;
                case Enum.DeepPink3:
                    return DeepPink3;
                case Enum.DeepPink2:
                    return DeepPink2;
                case Enum.DeepPink1:
                    return DeepPink1;
                case Enum.Raspberry:
                    return Raspberry;
                case Enum.HotPink4:
                    return HotPink4;
                case Enum.HotPink:
                    return HotPink;
                case Enum.HotPink1:
                    return HotPink1;
                case Enum.HotPink2:
                    return HotPink2;
                case Enum.VioletRed4:
                    return VioletRed4;
                case Enum.VioletRed3:
                    return VioletRed3;
                case Enum.VioletRed2:
                    return VioletRed2;
                case Enum.VioletRed1:
                    return VioletRed1;
                case Enum.HotPink3:
                    return HotPink3;
                case Enum.LavenderBlush4:
                    return LavenderBlush4;
                case Enum.LavenderBlush2:
                    return LavenderBlush2;
                case Enum.LavenderBlush3:
                    return LavenderBlush3;
                case Enum.LavenderBlush1:
                    return LavenderBlush1;
                case Enum.PaleVioletRed4:
                    return PaleVioletRed4;
                case Enum.PaleVioletRed:
                    return PaleVioletRed;
                case Enum.PaleVioletRed3:
                    return PaleVioletRed3;
                case Enum.PaleVioletRed2:
                    return PaleVioletRed2;
                case Enum.PaleVioletRed1:
                    return PaleVioletRed1;
                case Enum.Pink4:
                    return Pink4;
                case Enum.Pink2:
                    return Pink2;
                case Enum.Pink3:
                    return Pink3;
                case Enum.Pink1:
                    return Pink1;
                case Enum.Crimson:
                    return Crimson;
                case Enum.Pink:
                    return Pink;
                case Enum.LightPink:
                    return LightPink;
            }

            return Black;
        }
    }
}
